### ISSUE TITLE
User Security

### ISSUE THREAD

**Issue by superglubglub** [narmirarmi/CITS3403_Group_Project#13]
## Username and Password Security
- Hash passwords and prevent plaintext storage.
- Restrict usernames to exclude certain characters required by email regex (really we just should stop them from using the @ symbol)

## Browser Based Security
- Maintain a new table in the database called Session
- Session table stores user sessions (duh)
  - Session_ID column stores a hash of the user ID + the time of creation. This column must only contain unique variables. 
  - Session_Time column stores the time of session creation. This time must be referenced from the server, not the browser, to ensure users cannot set their session time in the future.

### Control Flow:
1. When a user navigates to the website, check if their browser has a Session variable in the LocalStorage
2. If the variable is not found, then start website loading
3. If the variable is found, then check if the session time is longer than 4 hours (or set some login timer variable to change this)
4. If the session has elapsed the login timer, then delete the session record and resume regular loading
5. If the session has not elapsed the login timer, then sign the user into their account and resume loading.

**Comment by superglubglub** [comment]
working on this in the user-management branch

**Comment by zazwaz12** [comment]
The user login "session" should only have the information of the current user logged in and everything else needs to be in the database.

**Comment by superglubglub** [comment]
Sessions and password security are implemented now, this issue can be closed.
