### ISSUE TITLE
Allow votes to persist between sessions

### ISSUE THREAD

**Issue by narmirarmi** [narmirarmi/CITS3403_Group_Project#22]
Users should be able to vote and then come back hours/ days later after closing their data and see the votes changed, other users on different devices, but the same database should see these votes reflected too.

**Comment by zazwaz12** [comment]
The votes are persisted to database in **user-management** as of right now.

 The issue is around assigning the current_users votes, as I set it up with just the dummy data of user id = 2.

**Comment by zazwaz12** [comment]
Now the votes are based solely on the user-logged in. This is resolved.
